### ISSUE TITLE
Period Problem

### ISSUE THREAD

**Issue by azim7091** [dwkim78/upsilon#7]
[lc_out00026.txt](https://github.com/dwkim78/upsilon/files/4674237/lc_out00026.txt)

Hi
I have a  light curve of an obvious variable with really obvious period, but the code cannot find the correct period? where does this problem come from and how can improve code ability to guess a better period?

I have attached the light curve, but let me know if you cannot find it (sorry, I am new to github).

**Comment by dwkim78** [comment]
Hi,

You first need to understand Lomb-Scargle algorithm which UPSILoN used to find period. Your lightcurve's periodogram looks like:
<img width="571" alt="Screen Shot 2020-05-25 at 9 49 02 AM" src="https://user-images.githubusercontent.com/7696163/82768946-07573100-9e6d-11ea-9cbc-79241ababc79.png">
, which is not ideal for finding period.

Cheers,

**Comment by azim7091** [comment]
Thank you so much for your responses.  I will check the algorithm. Another problem is about amplitude estimation, it is even worse. The code gives "amplitude', 141.59747680075938" which is wrong. 

Is it also related to Lomb-Scargle algorithm?


Best Regards
Azim

**Comment by kirxkirx** [comment]
If I may add... The input lightcurve is short: two consecutive cycles of a delta Scuti type variable. This is probably not what the code is expecting. But in principle, the lightcurve is sufficient to correctly determine the period and variability type. The trick is to restrict the trial period range to a sensible range (something like 0.1-0.01d) after visually inspecting the lightcurve and approximately guessing the period. In this particular case, the most important is to set the short-period limit of 0.01d in order to cut off the false peaks at high frequencies (where the period search algorithm is trying to fit a sine wave with a period equal to the distance between the constitutive data points -- this is not what we want to do physically and the amplitude of such wave will not be properly constrained, of course).

**Comment by azim7091** [comment]
Thanks a lot for the explanation.
I have checked this suggestion for the variable, and I found that it can identify the variable (DSCT) in a better way for fewer data points and gives a better estimation for period (2 times the real one).  But for very few data points (.01 day) the result is not acceptable.


I have attached the results. 
[13points.txt](https://github.com/dwkim78/upsilon/files/4683893/13points.txt)
[33points.txt](https://github.com/dwkim78/upsilon/files/4683870/33points.txt)
[45points.txt](https://github.com/dwkim78/upsilon/files/4683871/45points.txt)
[95points.txt](https://github.com/dwkim78/upsilon/files/4683872/95points.txt)
